### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by algodave** [bokmann/stonepath#4]
This project looks amazing, I starred and forked it!

I just found on https://github.com/bokmann/stonepath/blob/master/Manifest.txt many missing files:

```
lib/stonepath/acl.rb
lib/stonepath/controller_hooks.rb
lib/stonepath/group.rb
lib/stonepath/role.rb
lib/stonepath/acl/controller.rb
lib/stonepath/acl/role.rb
lib/stonepath/acl/state.rb
```

I guess they should implement "Access Control" as described on page 12 of 18 in `stonepath.pdf` right? Are you willing to provide them to the community or not? Thanks

**Comment by bokmann** [comment]
Stonepath's access control language was pulled out into a separate project, Stonewall (under the same github account).

But the current state of both gems requires a bit of explanation:

Both ere in heavy use in the Rails 2 days, but were never updated for Rails 3.  For Stonepath, this isn't a problem; Stonepath was just a simple 'wrapper' dsl on top of ActiveRecord conventions.  I still use the Stonepath methodology heavily, just mapping back to the ActiveRecord conventions (just using 'belongs_to' for 'owner', for instance.  Relying on the Acts as State MAchine gem, the Stonepath methodology is alive and well, and I've been threatening to document it more extensively than the article and few video presentations you can find online.

Stonewall is another story - The amount of metaprogramming it contained was.. messy.  The Rails 3 updates broke a lot.  And CanCan 'won' the authorization gem mindshare, so I just use it for these kinds of guards now.  Its not quite as 'fluent' for thinking along the lines of the 'stonepath way', but it works.
