### ISSUE TITLE
http://www.codesherpas.com/stonepath

### ISSUE THREAD

**Issue by bdmorin** [bokmann/stonepath#5]
http://www.codesherpas.com/stonepath is 404.

https://blog.codesherpas.com/ has an invalid SSL cert.

Project is dead?

**Comment by bokmann** [comment]
Please read the readme.  The gem is dead.  The methodology lives on, but needs documentation that lives beyond the project.

**Comment by bdmorin** [comment]
Sorry about that. Thnx.
